INSERT INTO employees (name, jobName, salaryGrade, department) VALUES
('John Doe', 'Software Engineer', 'A', 'IT'),
('Jane Smith', 'Data Analyst', 'B', 'Analytics'),
('Michael Johnson', 'HR Manager', 'C', 'Human Resources'),
('Emily Davis', 'Project Manager', 'B', 'Operations'),
('Daniel Brown', 'Marketing Specialist', 'C', 'Marketing'),
('Jessica Wilson', 'Sales Executive', 'B', 'Sales'),
('David Miller', 'Graphic Designer', 'B', 'Design'),
('Sarah Moore', 'Customer Support', 'C', 'Customer Service'),
('Robert Taylor', 'Business Analyst', 'A', 'Business Development'),
('James Anderson', 'DevOps Engineer', 'A', 'IT'),
('Jennifer Thomas', 'Content Writer', 'C', 'Marketing'),
('Chris Harris', 'Product Manager', 'B', 'Product'),
('Laura Martin', 'Financial Analyst', 'B', 'Finance'),
('Ryan Thompson', 'Systems Administrator', 'A', 'IT'),
('Sophia White', 'Legal Advisor', 'B', 'Legal'),
('Brandon Scott', 'HR Coordinator', 'C', 'Human Resources'),
('Olivia Clark', 'SEO Specialist', 'B', 'Marketing'),
('Matthew Lewis', 'Account Manager', 'B', 'Sales'),
('Megan Robinson', 'UX/UI Designer', 'A', 'Design'),
('Ethan Walker', 'Logistics Manager', 'C', 'Operations');
